// Sync lib/version.dart from pubspec.yaml's `version: X.Y.Z+N`.
// Run from the project root: `dart run tool/update_version.dart`.
// release.sh and the CI workflows call this so the in-app version always
// matches the published release.

import 'dart:io';

void main() {
  final pubspec = File('pubspec.yaml').readAsLinesSync();
  final line = pubspec.firstWhere(
    (l) => l.trimLeft().startsWith('version:'),
    orElse: () => '',
  );
  if (line.isEmpty) {
    stderr.writeln('No version: line in pubspec.yaml');
    exit(1);
  }
  final raw = line.split(':')[1].trim(); // e.g. 1.2.3+45
  final plus = raw.split('+');
  final version = plus[0];
  final build = plus.length > 1 ? int.tryParse(plus[1]) ?? 1 : 1;

  final out = '''
// GENERATED by tool/update_version.dart from pubspec.yaml — do not edit by hand.
// Run `dart run tool/update_version.dart` (release.sh / CI do this) to refresh.
//
// kAppVersion is the semantic version shown in the Update Center and compared
// against GitHub releases; kBuildNumber is the +N build (Android versionCode).

const String kAppVersion = '$version';
const int kBuildNumber = $build;
''';
  File('lib/version.dart').writeAsStringSync(out);
  stdout.writeln('lib/version.dart -> $version+$build');
}
